Add support for mongoid 8.
mongoid/mongoid-compatibility pull request #13
Opened 2022-08-16 07:39 UTC by joe1chen

This pull request adds support for Mongoid 8.

2022-08-16 15:18 UTC, dblock commented
Thanks! Looks like Travis-CI is RIP, would you care to do https://github.com/mongoid/mongoid-compatibility/issues/14 first so we can get CI back running here? You can look into https://github.com/dblock/slack-sup/blob/master/.github/workflows/test.yml for an example using MongoDB.

2022-08-16 19:45 UTC, joe1chen commented
@dblock Yep, I've been going through all my mongoid projects and updating them to use GHA. This pull request now includes a GHA file based on the ones that I've used for my other projects. In order to prevent the matrix from totally exploding, I've opted to only test the Mongoid versions with the Ruby version that was typically used with that version of Mongoid.

2022-08-16 19:48 UTC, joe1chen commented
The GHA is running 100% green. You can see the results here in my fork:

https://github.com/joe1chen/mongoid-compatibility/actions/runs/2870654375

2022-08-17 01:26 UTC, dblock commented
> I've opted to only test the Mongoid versions with the Ruby version that was typically used with that version of Mongoid. This pull fixes #14.

There's a much cleaner and shorter way to do this, a matrix with multiple variables: https://github.com/dblock/slack-ruby-client/blob/master/.github/workflows/test.yml#L7 - want to update?

2022-08-17 01:27 UTC, dblock commented on .github/workflows/test.yml
> +      matrix:
Make a matrix like https://github.com/dblock/slack-ruby-client/blob/master/.github/workflows/test.yml#L7 with ruby, mongodb and mongoid versions.

2022-08-17 18:56 UTC, joe1chen commented on .github/workflows/test.yml
> +      matrix:
Thanks, I knew there had to be a better way to do it.  Ok, let me update it with the new syntax.

2022-08-17 19:08 UTC, joe1chen commented on .github/workflows/test.yml
> +      matrix:
Ok, finished. The new syntax looks much cleaner. Thanks for the tip.

2022-08-17 20:50 UTC, dblock requested changes
Good! 

1. Re-add Danger, copy https://github.com/slack-ruby/slack-ruby-client/blob/master/.github/workflows/danger.yml
2. Update CHANGELOG (Danger would have caught it).
3. Increment version to 0.6.

2022-08-18 19:14 UTC, dblock requested changes
Looks great, one last small thing?

2022-08-18 19:14 UTC, dblock commented on CHANGELOG.md
> +### 0.6.1 (Next)
We haven't released 0.6.0, so this should be 0.6.0 (Next)

2022-08-18 19:14 UTC, dblock commented on .github/workflows/danger.yml
> +on: [push, pull_request]
Should only run on pull_request

2022-08-18 19:15 UTC, dblock commented on .github/workflows/test.yml
> +          mongodb-version: 3.6
We should also test against multiple versions of MongoDB, but can change this later.

2022-08-18 19:23 UTC, joe1chen commented on .github/workflows/danger.yml
> +on: [push, pull_request]
I added it so that I could actually test this step when pushing to my own branch. I will update the pull to remove the push.

2022-08-18 19:27 UTC, joe1chen commented
This pull is currently blocked by https://github.com/mongoid/danger/pull/5.  The mongoid-danger 0.1.1 gem requires danger 4.x, which doesn't support GHA.  Since GHA support was only added in danger 5.x, currently the danger execution fails with the error `Could not find the type of CI for Danger to run on.`.

2022-08-18 19:40 UTC, dblock commented on .github/workflows/danger.yml
> +on: [push, pull_request]
It won't work because it expects PR metadata

2022-08-18 20:40 UTC, joe1chen commented on CHANGELOG.md
> +### 0.6.1 (Next)
Fixed.

2022-08-18 20:40 UTC, joe1chen commented on .github/workflows/danger.yml
> +on: [push, pull_request]
Fixed.

2022-08-18 20:41 UTC, joe1chen commented
@dblock Once you have release mongoid-danger 0.1.2, we should update the Gemfile to use 0.1.2.

2022-08-18 21:15 UTC, joe1chen commented on .github/workflows/test.yml
> +          mongodb-version: 3.6
I've updated it to test from 3.6 to 5.0.  Currently there is no mongodb 6.0 docker image yet, so I didn't add 6.0 to the matrix.

2022-08-18 22:09 UTC, merged

2022-08-18 22:31 UTC, dblock commented
I did the upgrade in #15 and released 0.6.0. Thanks for your help @joe1chen! I could still use a co-maintainer if you're interessted, email me dblock at dblock dot org.